package hsfulda.bachelor.javacc.test;
/* Generated By:JavaCC: Do not edit this line. HilferufParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HilferufParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 5;
  /** RegularExpression Id. */
  int B = 6;
  /** RegularExpression Id. */
  int C = 7;
  /** RegularExpression Id. */
  int D = 8;
  /** RegularExpression Id. */
  int E = 9;
  /** RegularExpression Id. */
  int F = 10;
  /** RegularExpression Id. */
  int G = 11;
  /** RegularExpression Id. */
  int H = 12;
  /** RegularExpression Id. */
  int I = 13;
  /** RegularExpression Id. */
  int J = 14;
  /** RegularExpression Id. */
  int K = 15;
  /** RegularExpression Id. */
  int L = 16;
  /** RegularExpression Id. */
  int M = 17;
  /** RegularExpression Id. */
  int P = 18;
  /** RegularExpression Id. */
  int Q = 19;
  /** RegularExpression Id. */
  int R = 20;
  /** RegularExpression Id. */
  int T = 21;
  /** RegularExpression Id. */
  int U = 22;
  /** RegularExpression Id. */
  int V = 23;
  /** RegularExpression Id. */
  int X = 24;
  /** RegularExpression Id. */
  int Y = 25;
  /** RegularExpression Id. */
  int Z = 26;
  /** RegularExpression Id. */
  int N = 27;
  /** RegularExpression Id. */
  int O = 28;
  /** RegularExpression Id. */
  int S = 29;
  /** RegularExpression Id. */
  int W = 30;
  /** RegularExpression Id. */
  int HASH = 31;
  /** RegularExpression Id. */
  int ZAHL = 32;
  /** RegularExpression Id. */
  int GRAD = 33;
  /** RegularExpression Id. */
  int PUNKT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"._#\"",
    "\"_...#\"",
    "\"_._.#\"",
    "\"_..#\"",
    "\".#\"",
    "\".._.#\"",
    "\"__.#\"",
    "\"....#\"",
    "\"..#\"",
    "\".___#\"",
    "\"_._#\"",
    "\"._..#\"",
    "\"__#\"",
    "\".__.#\"",
    "\"__._#\"",
    "\"._.#\"",
    "\"_#\"",
    "\".._#\"",
    "\"..._#\"",
    "\"_..._#\"",
    "\"_.__#\"",
    "\"__..#\"",
    "\"_.#\"",
    "\"___#\"",
    "\"...#\"",
    "\".__#\"",
    "\"#\"",
    "<ZAHL>",
    "\"\\u00b0\"",
    "\".\"",
  };

}
