package hsfulda.bachelor.javacc.test;
/* Generated By:JavaCC: Do not edit this line. HilferufParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HilferufParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int N = 5;
  /** RegularExpression Id. */
  int G = 6;
  /** RegularExpression Id. */
  int O = 7;
  /** RegularExpression Id. */
  int S = 8;
  /** RegularExpression Id. */
  int W = 9;
  /** RegularExpression Id. */
  int ZAHLGRAD = 10;
  /** RegularExpression Id. */
  int MINPUNKTSEK = 11;
  /** RegularExpression Id. */
  int SOS = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"_.#\"",
    "\"__.#\"",
    "\"___#\"",
    "\"...#\"",
    "\".__#\"",
    "<ZAHLGRAD>",
    "<MINPUNKTSEK>",
    "\"...#___#...#\"",
    "\"#\"",
    "\"##\"",
  };

}
